### ISSUE TITLE
Submit to Typst Universe?

### ISSUE THREAD

**Issue by Antosser** [hzkonor/bubble-template#2]
Love the template! Could you please submit to Typst Universe for convenience. I'm sure a lot of people would use it!

**Comment by hzkonor** [comment]
> Love the template! Could you please submit to Typst Universe for convenience. I'm sure a lot of people would use it!

Thanks for your feedback, I will look into it :)

**Comment by hzkonor** [comment]
It has been merged [here](https://github.com/typst/packages/pull/534)

**Comment by Antosser** [comment]
Love it! Thx!

**Comment by sayan01** [comment]
Can you update the version present in typst universe? It seems to still hard-code the highlight for "highlight" and the `color-words` is not present.

**Comment by hzkonor** [comment]
> Can you update the version present in typst universe? It seems to still hard-code the highlight for "highlight" and the `color-words` is not present.

Yes I'll do that this week !

**Comment by hzkonor** [comment]
@sayan01 it has been updated [here](https://github.com/typst/packages/pull/830)
