### ISSUE TITLE
Do not hardcode language

### ISSUE THREAD

**Issue by SkytAsul** [hzkonor/bubble-template#4]
Hey! First, thanks for your template it is really clean and good-looking :)
I noticed that you hardcoded the french language for text here:
https://github.com/hzkonor/bubble-template/blob/ff3567f4e9d0d74039b6bf34d2eb368280d20360/template.typ#L40

I'd suggest you either change it to "auto" or completely remove this parameter from the set rule, because it does not really make sense for the template to handle it.

(bien que je sois français aussi hahaha)

**Comment by Aaron-Rumpler** [comment]
The version on Typst Universe still sets the language.

**Comment by hzkonor** [comment]
> The version on Typst Universe still sets the language.

Thanks for noticing, I fixed it [here](https://github.com/typst/packages/pull/1132)
